### ISSUE TITLE
conflicting dependancy issue 

### ISSUE THREAD

**Issue by PS-PRANAV4** [codeinpython-org/codeinpython-main#7]
there is dependency conflict while installing packages from requirement.txt

the problem is with twillio and djangorestframework-jwt they depend upon different pyjwt the breif description of the error is given below

ERROR: Cannot install -r requirements.txt (line 20), -r requirements.txt (line 9) and PyJWT==1.7.1 because these package versions have conflicting dependencies.

The user requested PyJWT==1.7.1
    djangorestframework-jwt 1.11.0 depends on PyJWT<2.0.0 and >=1.5.2
    twilio 7.12.0 depends on PyJWT<3.0.0 and >=2.0.0
![Screenshot from 2022-08-10 10-34-17](https://user-images.githubusercontent.com/99676239/183820652-a77f9e41-cc30-44ff-a5ba-1f9cd732c33f.png)

if you made change according to the necessary dependency then it will be helpful for the developers who clone this project in the future

**Comment by codeinpython-org** [comment]
@PS-PRANAV4  Install these 3 packages manually on your machine 
djangorestframework-jwt==1.11.0
PyJWT==1.7.1
twilio==7.12.0
